server:
  port: 9001
  servlet:
    context-path: /base
spring:
  datasource:
    url: jdbc:mysql://rm-bp18u477k42fziy09do.mysql.rds.aliyuncs.com/base?serverTimezone=GMT%2B8
    username: base
    password: queue_0436
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 9
  application:
    name: base

logging:
  level:
    cn:
      queue:
        batch:
          mapper: trace