server:
  port: 9001
  servlet:
    context-path: /video
spring:
  datasource:
    url: jdbc:mysql://8.134.57.218:3306/ccoo?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      database: 9

easy-es:
  # 基础配置项
  enable: true
  address: 8.134.57.218:9200
  schema: http
#  username: elasticsearch
#  password: ovoAdmin123
  keep-alive-millis: 18000
  # 扩展的连接池配置项
  global-config:
    #smoothly:平滑模式, not_smoothly:非平滑模式, manual:手动模式
    process-index-mode: manual
    async-process-index-blocking: true
    print-dsl: false
    db-config:
      map-underscore-to-camel-case: true
      id-type: customize
      #      field-strategy: not_empty
      refresh-policy: immediate
      enable-track-total-hits: true

logging:
  level:
    cn:
      queue:
        batch:
          mapper: trace