server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/demo/**
        - id: fourm
          uri: lb://fourm
          predicates:
            - Path=/fourm/**
        - id: judge
          uri: lb://judge
          predicates:
            - Path=/judge/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
