server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/demo/**
        - id: fourm
          uri: lb://fourm
          predicates:
            - Path=/fourm/**
        - id: im-core
          uri: http://localhost:9000
          predicates:
            - Path=/im-core/**
        - id: video
          uri: http://localhost:9001
          predicates:
            - Path=/video/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
