server:
  port: 7001
  servlet:
    context-path: /judge
spring:
  datasource:
    url: jdbc:mysql://rm-bp18u477k42fziy09do.mysql.rds.aliyuncs.com/online_judge?serverTimezone=GMT%2B8
    username: online_judge
    password: queue_0436
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
      database: 9

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.queue.online_judge.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

logging:
  level:
    cn:
      queue:
        batch:
          mapper: trace

