server:
  port: 7001
  servlet:
    context-path: /online_judge
spring:
  datasource:
    url: jdbc:mysql://rm-bp18u477k42fziy09do.mysql.rds.aliyuncs.com/online_judge?serverTimezone=GMT%2B8
    username: online_judge
    password: queue_0436
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 9

logging:
  level:
    cn:
      queue:
        batch:
          mapper: trace