server:
  port: 9000
  servlet:
    context-path: /im-core
spring:
  datasource:
    url: jdbc:mysql://rm-bp18u477k42fziy09do.mysql.rds.aliyuncs.com:3306/im
    username: im
    password: queue_0436
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 9
mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.queue.**.domain
  configuration:
    cache-enabled: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn:
      queue:
        batch:
          mapper: trace