server:
  port: 9000
  servlet:
    context-path: /im-core
spring:
  datasource:
    url: jdbc:mysql://rm-bp18u477k42fziy09do.mysql.rds.aliyuncs.com:3306/im
    username: im
    password: queue_0436
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.queue.**.domain
  configuration:
    cache-enabled: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn:
      queue:
        batch:
          mapper: trace
rocketmq:
  name-server: 192.168.189.132:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: im-group
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false