server:
  port: 6000
  servlet:
    context-path: /file
spring:
  datasource:
    url: jdbc:mysql://rm-bp18u477k42fziy09do.mysql.rds.aliyuncs.com:3306/${table_name}?serverTimezone=GMT%2B8
    username: online_judge
    password: queue_0436
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 9

logging:
  level:
    cn:
      queue:
        batch:
          mapper: trace